apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: student-activity-actor-subscription # Descriptive name for the K8s resource
spec:
  topic: student-activity-topic # The topic our SubscriberActor will listen to
  pubsubname: student-pubsub # MUST MATCH the 'metadata.name' of your pub/sub component
  routes:
    default: /SubscriberActor/ReceiveStudentAction
  scopes:
    - learning-analytics-app # IMPORTANT: App-ID of the Dapr application running the SubscriberActor
    - memory-app
    - student-interaction-app
    - teacher-support-app
# https://docs.dapr.io/developing-applications/building-blocks/pubsub/howto-publish-subscribe/