apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: teacher-notification-subscription
spec:
  topic: teacher-notifications-topic
  pubsubname: student-pubsub
  routes:
    default: /SubscriberActor/ReceiveTeacherNotification
  scopes:
    - teacher-support-app
    - learning-analytics-app